### ISSUE TITLE
套餐详情能否适配json数据

### ISSUE THREAD

**Issue by hero866** [moeumwy/v2board-theme#3]
例如
[
    {
        "feature":"建议季付起购，每月 100G 流量",
        "support":true
    },
    {
        "feature":"全球 10+ 个国家接入",
        "support":true
    },
    {
        "feature":"限制3台客户端连接数量，不限速",
        "support":true
    },
    {
        "feature":"1Gbps 带宽保证",
        "support":true
    }
]

**Comment by moeumwy** [comment]
有空的时候可以考虑适配一下

**Comment by moeumwy** [comment]
已适配
https://github.com/moeumwy/v2board-theme/commit/6b7abea0b3b91ba192ba3e01157a2656c47281e6
