### ISSUE TITLE
请问如何适配更改过路径的订阅链接

### ISSUE THREAD

**Issue by koi778** [moeumwy/v2board-theme#4]
api路径之类的直接改api/v1，订阅链接的实在没找到应该修改哪里，请教一下应该怎么改（订阅链接的路径是通过反代实现的，默认路径还有一些用，所以没有直接从源站改）

**Comment by moeumwy** [comment]
路径默认前缀“/api/v1/”由src/middleware/api/index.ts统一配置

**Comment by koi778** [comment]
感谢大佬回复，我的意思是“/client/subscribe?token” 在项目中有拼接的地方吗？根据关键词是没搜索到的。默认的不是 https://domain/api/v1/client/subscribe?token=*** 吗，比如我改成了 https://domain/sub?key=***** ，该如何改项目的代码来适配

**Comment by moeumwy** [comment]
你举例的订阅链接请求是由“/api/v1/user/getSubscribe”接口返回的，即是在后端PHP中自定义的。其他请求的路径或参数修改可在src/store/services/api.ts

**Comment by koi778** [comment]
明白了，感谢大佬
